### ISSUE TITLE
Does not work with 3,5" LCD

### ISSUE THREAD

**Issue by marekzima** [lbt/python-gui#2]
I've tried it with 3,5" LCD and I'm getting error: "Could not find DRM device", so I'm going back to X :(

**Comment by lbt** [comment]
Since there's no meaningful information about your setup or how/when the problem occurs and since you've already decided to go back to X11 then I'll close this

**Comment by marekzima** [comment]
Setup was very easy:
1. Raspbian Pi BullsEye on Raspberry Pi 3B
2. installed LCD-show (https://github.com/goodtft/LCD-show.git)
--- so I see booting proces and shell on that small 3,5" LCD
3. Went through your steps
4. After run ./gui.py - I've got Error message "Could not find DRM device"

That's all :)

**Comment by lbt** [comment]
You don't mention your OS version and I'm not sure if that setup will support the DRM driver (ie vc4-kms-v3d in boot/config.txt)
If you get 3D acceleration under X11 then it should work using the framebuffer too.
